const DEFAULT_VIOLATION_TYPES = [
  {
    code: "DL_EXP",
    name: "Expired Driving License",
    description: "Driving with an expired driving license.",
    fineAmount: 5000,
    severity: "high",
    points: 10,
    applicableTo: ["driver"],
    status: "active",
  },
  {
    code: "DL_RENEW_LATE",
    name: "Late License Renewal Penalty",
    description:
      "Monthly penalty for not renewing an expired driving license after the allowed due date.",
    fineAmount: 500,
    severity: "medium",
    points: 5,
    applicableTo: ["driver"],
    status: "active",
  },
  {
    code: "REG_EXP",
    name: "Expired Vehicle Registration",
    description: "Vehicle registration certificate is expired.",
    fineAmount: 10000,
    severity: "high",
    points: 10,
    applicableTo: ["owner"],
    status: "active",
  },
  {
    code: "FIT_EXP",
    name: "Expired Fitness Certificate",
    description: "Vehicle fitness certificate is expired.",
    fineAmount: 7000,
    severity: "high",
    points: 8,
    applicableTo: ["owner"],
    status: "active",
  },
  {
    code: "TAX_EXP",
    name: "Expired Tax Token",
    description: "Vehicle tax token is expired.",
    fineAmount: 3000,
    severity: "medium",
    points: 4,
    applicableTo: ["owner"],
    status: "active",
  },
  {
    code: "INS_EXP",
    name: "Expired Insurance",
    description: "Vehicle insurance is expired.",
    fineAmount: 5000,
    severity: "medium",
    points: 5,
    applicableTo: ["owner"],
    status: "active",
  },
  {
    code: "NO_DL",
    name: "Driving Without License",
    description: "Driving without a valid driving license.",
    fineAmount: 25000,
    severity: "critical",
    points: 20,
    applicableTo: ["driver"],
    status: "active",
  },
  {
    code: "UNAUTH_DRV",
    name: "Unauthorized Driver",
    description:
      "Vehicle operated by a driver who is not authorized or assigned.",
    fineAmount: 15000,
    severity: "critical",
    points: 15,
    applicableTo: ["driver", "owner"],
    status: "active",
  },
  {
    code: "ROUTE_EXP",
    name: "Expired Route Permit",
    description: "Route permit is expired or invalid.",
    fineAmount: 8000,
    severity: "high",
    points: 8,
    applicableTo: ["owner"],
    status: "active",
  },
  {
    code: "OVERLOAD",
    name: "Overloading",
    description:
      "Vehicle is carrying passengers or goods beyond the legal limit.",
    fineAmount: 10000,
    severity: "high",
    points: 10,
    applicableTo: ["driver", "owner"],
    status: "active",
  },
  {
    code: "SIGNAL",
    name: "Traffic Signal Violation",
    description: "Ignoring or violating traffic signal instructions.",
    fineAmount: 5000,
    severity: "medium",
    points: 6,
    applicableTo: ["driver"],
    status: "active",
  },
  {
    code: "SPEED",
    name: "Speeding",
    description: "Driving above the allowed speed limit.",
    fineAmount: 5000,
    severity: "high",
    points: 8,
    applicableTo: ["driver"],
    status: "active",
  },
  {
    code: "RECKLESS",
    name: "Reckless Driving",
    description: "Dangerous or reckless driving behavior.",
    fineAmount: 20000,
    severity: "critical",
    points: 20,
    applicableTo: ["driver"],
    status: "active",
  },
  {
    code: "PARKING",
    name: "Illegal Parking",
    description: "Parking vehicle in a restricted or illegal area.",
    fineAmount: 2000,
    severity: "low",
    points: 2,
    applicableTo: ["driver"],
    status: "active",
  },
  {
    code: "HELMET",
    name: "No Helmet",
    description: "Riding motorcycle without wearing a helmet.",
    fineAmount: 1000,
    severity: "medium",
    points: 3,
    applicableTo: ["driver"],
    status: "active",
  },
  {
    code: "SEATBELT",
    name: "No Seatbelt",
    description:
      "Driving or riding without using seatbelt where applicable.",
    fineAmount: 1000,
    severity: "medium",
    points: 3,
    applicableTo: ["driver"],
    status: "active",
  },
  {
    code: "BLACKLIST",
    name: "Blacklisted Vehicle",
    description: "Vehicle is blacklisted or suspended by authority.",
    fineAmount: 50000,
    severity: "critical",
    points: 25,
    applicableTo: ["owner"],
    status: "active",
  },
];

module.exports = {
  DEFAULT_VIOLATION_TYPES,
};