const mongoose = require("mongoose");

const violationSchema = new mongoose.Schema(
  {
    caseId: {
      type: String,
      required: true,
      unique: true,
      trim: true,
    },

    vehicle: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Vehicle",
      index: true,
    },

    registrationNumber: {
      type: String,
      uppercase: true,
      trim: true,
      index: true,
    },

    driver: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      index: true,
    },

    license: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "DrivingLicense",
      index: true,
    },

    licenseNumber: {
      type: String,
      uppercase: true,
      trim: true,
      index: true,
    },

    officer: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
      index: true,
    },

    violationTypeRef: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "ViolationType",
      index: true,
    },

    violationType: {
      type: String,
      required: true,
      trim: true,
    },

    violationCode: {
      type: String,
      trim: true,
      uppercase: true,
      index: true,
    },

    violationSnapshot: {
      code: {
        type: String,
        trim: true,
        uppercase: true,
      },
      name: {
        type: String,
        trim: true,
      },
      description: {
        type: String,
        trim: true,
      },
      fineAmount: {
        type: Number,
        min: 0,
      },
      severity: {
        type: String,
        enum: ["low", "medium", "high", "critical"],
      },
      points: {
        type: Number,
        min: 0,
        default: 0,
      },
      applicableTo: [
        {
          type: String,
          enum: ["driver", "owner"],
        },
      ],
    },

    responsibility: {
      type: String,
      enum: ["owner", "driver", "both"],
      default: "owner",
      index: true,
    },

    description: {
      type: String,
      trim: true,
    },

    location: {
      address: String,
      city: String,
      district: String,
      lat: Number,
      lng: Number,
    },

    fineAmount: {
      type: Number,
      required: true,
      min: 0,
    },

    currency: {
      type: String,
      default: "BDT",
    },

    evidence: [
      {
        type: {
          type: String,
          enum: ["image", "video", "document", "note", "text"],
          default: "note",
        },
        url: String,
        description: String,
        uploadedAt: {
          type: Date,
          default: Date.now,
        },
      },
    ],

    status: {
      type: String,
      enum: ["pending", "approved", "dismissed", "paid", "unpaid"],
      default: "pending",
      index: true,
    },

    paymentStatus: {
      type: String,
      enum: ["unpaid", "paid", "partial", "waived", "pending"],
      default: "unpaid",
      index: true,
    },

    paymentDate: Date,
    paidAt: Date,

    payment: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Payment",
    },

    adminReviewedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
    },

    adminReviewNote: String,
    reviewNote: String,
    reviewedAt: Date,
    adminReviewedAt: Date,

    source: {
      type: String,
      enum: ["police", "admin", "system"],
      default: "police",
      index: true,
    },

    reviewMode: {
      type: String,
      enum: ["manual", "system"],
      default: "manual",
      index: true,
    },

    reviewRequired: {
      type: Boolean,
      default: true,
      index: true,
    },

    ruleCode: {
      type: String,
      trim: true,
      index: true,
    },

    confidenceScore: {
      type: Number,
      min: 0,
      max: 100,
    },

    dueDate: {
      type: Date,
      index: true,
    },

    automationKey: {
      type: String,
      unique: true,
      sparse: true,
      trim: true,
      index: true,
    },

    autoGenerated: {
      type: Boolean,
      default: false,
      index: true,
    },

    safetySnapshot: {
      vehicleScore: Number,
      driverScore: Number,
      riskLevel: String,
      issues: [
        {
          code: String,
          message: String,
          severity: String,
          penalty: Number,
        },
      ],
    },

    issuedAt: {
      type: Date,
      default: Date.now,
      index: true,
    },
  },
  { timestamps: true }
);

module.exports =
  mongoose.models.Violation ||
  mongoose.model("Violation", violationSchema, "violations");